### ISSUE TITLE
Filter to be fixed 

### ISSUE THREAD

**Issue by aritra31** [First-project-01/Django-ecommerce#12]
Kindly fix the filter which will go through the category, price and discounted_price if present and size.

**Comment by FIRDOUS-BHAT** [comment]
You haven't described the issue in detail along with the code snippet where you exactly are facing this issue :)

**Comment by aritra31** [comment]
The price filter isn't working properly. I want a Sort By function which
will sort it from Newest, low to high and high to low. Also, in the price
filter, I want it to get filtered by discount if the product has one.

**Comment by FIRDOUS-BHAT** [comment]
As you havn't provided the exact code snippet over here so it's unclear for me to provide any fixture.

I suggest you to go through the docs,

https://django-filter.readthedocs.io/en/stable/guide/tips.html

**Comment by aritra31** [comment]
#products-html
 
    <div class="row">
      <div class="container">
          <form method="get"style="width:20%">
            {{filter.form|crispy}}
            <div class="row">
              <label>Select sorting criteria</label>
              <div class="control">
                  <div class="select">
                      <select name="sorting">
                          <option value="-date_added"{% if sorting ==
'-date_added' %}selected{% endif %}>Latest collection</option>
                          <option value="price"{% if sorting == 'price' %}
selected {% endif %}>Lowest to Highest</option>
                          <option value="-price"{% if sorting == '-price' %}
 selected {% endif %}>Highest to Lowest</option>
                      </select>
                  </div>
              </div>
          </div>
            <button type="submit" class="btn btn-warning btn-sm"><span class
="glyphicon glyphicon-search"></span> Search</button>
        </form>
      </div>
    </div>

#views.py

class Product(ListView):
    model = Items
    paginate_by = 6
    template_name = 'products.html'
    ordering = ["-id"]

    def get_queryset(self):
        queryset = super().get_queryset()
        filter = ProductFilter(self.request.GET, queryset)
        return filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        filter = ProductFilter(self.request.GET, queryset)
        context["filter"] = filter
        return context

# filters.py
import django_filters
from .models import Items

class ProductFilter(django_filters.FilterSet):
    class Meta:
        model = Items
        fields = ['size', 'category']
